spring:
  datasource:
    url: jdbc:mysql://192.168.0.8:3316/mcms-5.1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: mcms
    password: mcms
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource